export type Locale = 'zh' | 'en'

export const copy = {
  zh: {
    nav: {
      atlas: '图谱',
      graph: '关系',
      timeline: '时间线',
      about: '阅读指南',
      github: 'GitHub',
    },
    hero: {
      titleA: '读懂 AI 人名术语',
      titleB: '背后的思想。',
      description: '从直觉、数学、历史与关联出发，理解这些概念如何用于现代 AI。',
      primary: '探索图谱',
      secondary: '如何阅读一条概念',
    },
    atlas: {
      title: '先看懂它做什么，再记住它叫什么',
      description: '按正式术语、人名、功能或 AI 用途搜索。',
      search: '搜索人名、术语、功能或 AI 用途…',
      concepts: '概念',
      people: '人物',
      filters: '筛选',
      surprise: '随机探索',
      all: '全部',
      results: '条结果',
      clear: '清除',
      noResults: '没有找到匹配条目。试试 “curvature”、“概率更新” 或 “robotics”。',
      plainLabel: '一句话含义',
      namedAfter: '名字来源',
      usedIn: 'AI 用途',
    },
    detail: {
      back: '返回结果',
      question: '它回答什么问题？',
      intuition: '15 秒直觉',
      formal: '形式化定义',
      ai: '为什么对 AI 重要',
      related: '相关概念',
      attribution: '名字与归因',
      sources: '来源',
      copyLink: '复制链接',
      copied: '链接已复制',
      improve: '在 GitHub 改进此条目',
      openFull: '打开完整条目',
      attributionGuard: '术语以谁命名，不等于谁独立发现了它。',
    },
    graph: {
      title: '概念之间如何关联',
      description: '从一个概念出发，追踪命名来源、相关思想与 AI 用途。',
      focus: '聚焦一个概念…',
      depth: '深度',
      show: '显示',
      people: '人物',
      concepts: '概念',
      applications: 'AI 应用',
      list: '关系列表',
      reset: '重置视图',
      builtFrom: '建立在',
      usedBy: '被这些方法使用',
      paired: '常一起出现',
    },
    timeline: {
      title: '从原始工作到现代 AI',
      description: '查看概念何时出现、如何得名，以及后来怎样进入 AI。',
      all: '全部事件',
      person: '人物',
      publication: '发表',
      naming: '命名',
      ai: 'AI 采用',
    },
  },
  en: {
    nav: {
      atlas: 'Atlas',
      graph: 'Graph',
      timeline: 'Timeline',
      about: 'How to read',
      github: 'GitHub',
    },
    hero: {
      titleA: 'Understand the ideas',
      titleB: 'behind the names in AI.',
      description: 'Explore the intuition, mathematics, history, connections, and modern AI uses of concepts named after people.',
      primary: 'Explore the atlas',
      secondary: 'How to read an entry',
    },
    atlas: {
      title: 'Understand what it does. Then remember the name.',
      description: 'Search by formal term, person, function, or AI use.',
      search: 'Search a person, term, function, or AI use…',
      concepts: 'Concepts',
      people: 'People',
      filters: 'Filters',
      surprise: 'Surprise me',
      all: 'All',
      results: 'results',
      clear: 'Clear',
      noResults: 'No matching entries. Try “curvature”, “belief update”, or “robotics”.',
      plainLabel: 'Plain-language meaning',
      namedAfter: 'Named after',
      usedIn: 'Used in AI',
    },
    detail: {
      back: 'Back to results',
      question: 'What question does it answer?',
      intuition: '15-second intuition',
      formal: 'Formal definition',
      ai: 'Why it matters in AI',
      related: 'Related concepts',
      attribution: 'Name & attribution',
      sources: 'Sources',
      copyLink: 'Copy link',
      copied: 'Link copied',
      improve: 'Improve this entry on GitHub',
      openFull: 'Open full entry',
      attributionGuard: 'An eponym records naming history; it does not necessarily identify a sole discoverer.',
    },
    graph: {
      title: 'How concepts connect',
      description: 'Start with one concept and trace its namesakes, related ideas, and AI uses.',
      focus: 'Focus a concept…',
      depth: 'Depth',
      show: 'Show',
      people: 'People',
      concepts: 'Concepts',
      applications: 'AI applications',
      list: 'List relationships',
      reset: 'Reset view',
      builtFrom: 'Built from',
      usedBy: 'Used by',
      paired: 'Often paired with',
    },
    timeline: {
      title: 'From original work to modern AI',
      description: 'See when an idea was published, named, and later adopted in AI.',
      all: 'All events',
      person: 'People',
      publication: 'Publication',
      naming: 'Naming',
      ai: 'AI adoption',
    },
  },
} as const
