export type Locale = 'zh' | 'en'

export const copy = {
  zh: {
    nav: {
      atlas: '图谱',
      graph: '关系',
      timeline: '时间线',
      about: '方法',
      github: 'GitHub',
    },
    hero: {
      titleA: 'From Names to Meaning,',
      titleB: 'From Mathematics to AI.',
      description: '解读人工智能背后的人物、数学与思想。',
      primary: '探索图谱',
      secondary: '如何阅读一条概念',
    },
    atlas: {
      title: '先理解意义，再记住名字',
      description: '搜索正式术语、人名、功能解释，或它在 AI 里的用途。',
      search: '搜索人名、术语、功能或 AI 用途…',
      concepts: '概念',
      people: '人物',
      filters: '筛选',
      surprise: '随机探索',
      all: '全部',
      results: '条结果',
      clear: '清除',
      noResults: '没有找到匹配条目。试试 “curvature”、“概率更新” 或 “robotics”。',
      plainLabel: 'Atlas 功能标签',
      namedAfter: '名字来源',
      usedIn: 'AI 用途',
    },
    detail: {
      back: '返回结果',
      question: '它回答什么问题？',
      intuition: '15 秒直觉',
      formal: '形式化定义',
      ai: '为什么对 AI 重要',
      related: '相关概念',
      attribution: '名字与归因',
      sources: '来源',
      copyLink: '复制链接',
      copied: '链接已复制',
      improve: '在 GitHub 改进此条目',
      openFull: '打开完整条目',
      attributionGuard: '人名术语记录命名史，并不一定代表某人独立发现。',
    },
    graph: {
      title: '思想如何连接',
      description: '从一个概念出发，只追踪有明确意义的关系。',
      focus: '聚焦一个概念…',
      depth: '深度',
      show: '显示',
      people: '人物',
      concepts: '概念',
      applications: 'AI 应用',
      list: '关系列表',
      reset: '重置视图',
      builtFrom: '建立在',
      usedBy: '被这些方法使用',
      paired: '常一起出现',
    },
    timeline: {
      title: '从发表到现代 AI',
      description: '区分人物、发表、命名传播与 AI 采用，而不把历史压成一个名字。',
      all: '全部事件',
      person: '人物',
      publication: '发表',
      naming: '命名',
      ai: 'AI 采用',
    },
  },
  en: {
    nav: {
      atlas: 'Atlas',
      graph: 'Graph',
      timeline: 'Timeline',
      about: 'Method',
      github: 'GitHub',
    },
    hero: {
      titleA: 'From Names to Meaning,',
      titleB: 'From Mathematics to AI.',
      description: 'Decoding the people, mathematics, and ideas behind artificial intelligence.',
      primary: 'Explore the atlas',
      secondary: 'How to read an entry',
    },
    atlas: {
      title: 'Meaning first. Names second.',
      description: 'Search a formal term, a person, what it does, or where it appears in AI.',
      search: 'Search a person, term, function, or AI use…',
      concepts: 'Concepts',
      people: 'People',
      filters: 'Filters',
      surprise: 'Surprise me',
      all: 'All',
      results: 'results',
      clear: 'Clear',
      noResults: 'No matching entries. Try “curvature”, “belief update”, or “robotics”.',
      plainLabel: 'Atlas plain-language label',
      namedAfter: 'Named after',
      usedIn: 'Used in AI',
    },
    detail: {
      back: 'Back to results',
      question: 'What question does it answer?',
      intuition: '15-second intuition',
      formal: 'Formal definition',
      ai: 'Why it matters in AI',
      related: 'Related concepts',
      attribution: 'Name & attribution',
      sources: 'Sources',
      copyLink: 'Copy link',
      copied: 'Link copied',
      improve: 'Improve this entry on GitHub',
      openFull: 'Open full entry',
      attributionGuard: 'An eponym records naming history; it does not necessarily identify a sole discoverer.',
    },
    graph: {
      title: 'How the ideas connect',
      description: 'Start with one concept. Follow only the relationships that carry meaning.',
      focus: 'Focus a concept…',
      depth: 'Depth',
      show: 'Show',
      people: 'People',
      concepts: 'Concepts',
      applications: 'AI applications',
      list: 'List relationships',
      reset: 'Reset view',
      builtFrom: 'Built from',
      usedBy: 'Used by',
      paired: 'Often paired with',
    },
    timeline: {
      title: 'From publication to modern AI',
      description: 'Separate people, publication, naming, and AI adoption instead of flattening history into a name.',
      all: 'All events',
      person: 'People',
      publication: 'Publication',
      naming: 'Naming',
      ai: 'AI adoption',
    },
  },
} as const
